### ISSUE TITLE
matcaffe 问题

### ISSUE THREAD

**Issue by panmyuan** [ArcherFMY/AFNet#3]
![image](https://user-images.githubusercontent.com/48192787/56422602-dc4df580-62da-11e9-8fe0-ef9cca3c77fc.png)
百度查了很多，都没解决这个问题，希望有人可以帮忙解决一下

**Comment by ArcherFMY** [comment]
This may help you for the hdf5 error
https://github.com/BVLC/caffe/issues/4333

Regarding the opencv_imgcodecs error, please check if you have OpenCV 3.0+ installed on your computer. This code has been successfully tested with OpenCV 3.1.0. 
This link may help you
https://github.com/BVLC/caffe/issues/4942

**Comment by panmyuan** [comment]
ok, i willl try it. Thanks
