### ISSUE TITLE
 "caffe.LayerParameter" has no field named "interp_param"

### ISSUE THREAD

**Issue by sunkyya** [ArcherFMY/AFNet#5]
Wrong message:
Protobuf : Error parsing text-format caffe.NetParameter: 2095:18: Message type "caffe.LayerParameter" has no field named "interp_param". . at
D:\ThirdPartyLibrary\protobuf\src\google\protobuf\text_format.cc Line 296

My enviroment:
caffe: happynear/caffe(https://github.com/happynear/caffe-windows)
cuda: 9.1
python: 3.5

Should i rebuild caffe from your repo?

**Comment by ArcherFMY** [comment]
yes.

you can use caffe from this repo or add ‘interp’ layer into your current caffe.

**Comment by sunkyya** [comment]
@ArcherFMY  thx ! i have solved this problem~

**Comment by GuoQingqing** [comment]
Hi, I have met the problem. How do you solve this problem?
