### ISSUE TITLE
wrong saliency map in ECSSD 

### ISSUE THREAD

**Issue by Mhaiyang** [ArcherFMY/AFNet#7]
The provided saliency map 0557 in ECSSD dataset has a resolution of 617*464. The original image, however, has a size of 400*299. How could I compute the F score and mae?

**Comment by ArcherFMY** [comment]
The original image in ECSSD dataset is a gray image. Many methods replace it with a color image or just delete it and then compute the F-score/MAE for 999 images.

We provide our saliency map of the original image below.

![0557](https://user-images.githubusercontent.com/11482534/60440673-e334a500-9c47-11e9-8b8a-e195aecc9702.png)
